name: Update monthly delays chart

on:
  push:
    branches:
      - erik
  pull_request:
    branches:
      - erik

jobs:
  update_monthly_delays_chart:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ github.workspace }}/R/library  # Define library path

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scipy numpy pyarrow requests

    - name: Run Python script
      run: |
        cd code
        python get_filtered_weekends_vacation_covid_delays.py

    - name: Commit filtered weekends vacation covid delays
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/output/filtered_weekends_vacation_covid_delays.feather
        git commit -m 'Update filtered weekends vacation covid delays'
        git push

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-
    
    - name: Install R dependencies
      run: |
        sudo apt-get install pandoc
        Rscript -e 'install.packages(c("dplyr", "readr", "lubridate", "reticulate", "tidyr", "highcharter", "htmlwidgets", "arrow", "pandoc"), repos="https://cloud.r-project.org/")'
    

    - name: Run R script
      run: |
        cd code
        Rscript get_num_monthly_delays.r

    - name: Commit num monthly delays
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add visuals/num_monthly_delays1.html
        git commit -m 'Update num monthly delays'
        git push